# Generated by Django 5.2.3 on 2025-06-25 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagem', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viagem',
            options={'ordering': ['-data_saida'], 'verbose_name': 'Viagem', 'verbose_name_plural': 'Viagens'},
        ),
        migrations.RemoveField(
            model_name='viagem',
            name='data_ida',
        ),
        migrations.RemoveField(
            model_name='viagem',
            name='data_volta',
        ),
        migrations.RemoveField(
            model_name='viagem',
            name='origem',
        ),
        migrations.RemoveField(
            model_name='viagem',
            name='responsavel',
        ),
        migrations.AddField(
            model_name='viagem',
            name='data_retorno',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viagem',
            name='data_saida',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viagem',
            name='motorista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viagens_como_motorista', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='viagem',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='viagem',
            name='status',
            field=models.CharField(choices=[('AGENDADA', 'Agendada'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='AGENDADA', max_length=20),
        ),
    ]
