# Generated by Django 5.2.3 on 2025-06-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('placa', models.CharField(max_length=10)),
                ('disponivel', models.BooleanField(default=True)),
            ],
        ),
    ]
