# Generated by Django 5.2.3 on 2025-06-24 18:51

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('veiculo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('mecanico', 'Mecânico'), ('lavagem', 'Lavagem'), ('outro', 'Outro')], max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('data_inicio', models.DateTimeField(default=datetime.datetime.now)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veiculo.veiculo')),
            ],
        ),
    ]
